

GET http://localhost:666/orders
Content-Type: application/json

GET http://localhost:666/orders?patient_id=13&&samplekind=bloodTest&&date=2022-11-03
Content-Type: application/json



POST http://localhost:666/orders/
Content-Type: application/json
{
    "date": "2022-11-05"
     ,"sampleList": [ {
        "patientId":"14",
        "kind": "bloodTest"
    },{
        "patientId":"15",
        "kind": "covidTest"
    },{
        "patientId":"16",
        "kind": "covidTest"
    },{
        "patientId":"17",
        "kind": "bloodTest"
    }]
   
}

POST http://localhost:666/patients/
Content-Type: application/json
{
    "firstName": "Tomasz",
    "lastName": "prazniewski",
    "email": "tomaszprazniewskiab@gmail.com",
    "dateOfBirth": "1989-08-09 19:55:12"
}

