

GET http://localhost:666/orders
Content-Type: application/json

GET http://localhost:666/orders?patient_id=4&&samplekind=bloodTest
Content-Type: application/json



POST http://localhost:666/orders/
Content-Type: application/json
{
    "date": "2022-11-03 19:13:13"
     ,"sampleList": [ {
        "patientId":"10",
        "kind": "bloodTest"
    },{
        "patientId":"11",
        "kind": "covidTest"
    },{
        "patientId":"12",
        "kind": "covidTest"
    },{
        "patientId":"13",
        "kind": "bloodTest"
    }]
   
}

POST http://localhost:666/patients/
Content-Type: application/json
{
    "firstName": "Edyta",
    "lastName": "Prazniewska",
    "email": "edytaaaa@gmail.com",
    "dateOfBirth": "1989-08-05"
}

